###
POST http://localhost:8080/__admin/mappings
Content-Type: application/json

{
  "name": "Simple stub - hello world!",
  "request": {
    "method": "GET",
    "url": "/hello"
  },
  "response": {
    "status": 200,
    "jsonBody": {
      "message" : "Hello"
    },
    "headers": {
      "Content-Type": "application/json"
    }
  }
}
